config/routes.rb
Rails.application.routes.draw do
  root to: "pages#index"

  devise_for :users

  resources :users, only: [:index, :show, :destroy]
  match '/users/admin/new', via: :get, to: 'users#new'
  match '/users/admin/new', via: :post, to: 'users#create'

  match '/pets/search', via: :get, to: 'pets#search'
  resources :pets do
    resources :messages, only: [:new, :create]
  end



end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    alias_action :update, :destroy, to: :modify
    if user
      if user.role == 'admin'
        can :manage, :all
        cannot :delete, User do |account|
          account.role == 'admin'
        end
      elsif user.role == 'user'
        can :show, User do |account|
          account == user
        end
        can [:read, :create], Pet
        can :modify, Pet do |pet|
          pet.try(:user) == user
        end
      end
    else
      can :read, Pet
    end
  end
end

app/models/color.rb
class Color < ActiveRecord::Base
  validates :name, presence: true

  has_and_belongs_to_many :pets
end

app/models/concerns/filterable.rb
module Filterable
  extend ActiveSupport::Concern

  module ClassMethods
    def filter(filtering_params)
      results = self.where(nil)
      filtering_params.each do |key, value|
        results = results.public_send(key, value) if value.present?
      end
      results
    end
  end
end

app/models/message.rb
class Message
  attr_reader :owner_email, :owner_phone, :message, :sender_email

  def initialize(info)
    @owner_email = info['owner_email']
    @owner_phone = info['owner_phone']
    @message = info['message']
    @sender_email = info['sender_email']
  end
end

app/models/pet.rb
class Pet < ActiveRecord::Base
  include Filterable

  GENDERS = ['Male','Female', 'Unknown']
  AGES = ['1-5', '6-10', '10+', 'Unknown']
  TYPES = ['Dog', 'Cat', 'Rodent', 'Misc. mammal', 'Bird', 'Reptile', 'Amphibian', 'Anthropod']
  LOCATIONS = ['Downtown', 'NE Portland', 'NW Portand', 'SE Portland', 'SW Portland', 'N Portland',
               'Beaverton', 'Gresham', 'Clackamas', 'Tigard', 'Tualatin', 'Happy Valley', 'Milwaukie',
               'Lake Oswego', 'Hilsboro', 'Aloha', 'West Linn', 'Oregon City', 'Troutdale', 'Wood Village', 'Fairview']
  COLORS = %w(Brown Black White Gray Yellow Green Red Blue)

  scope :lost, -> (bool=true) { self.where(lost: bool) }
  scope :found, -> { self.where(lost: false) }
  scope :species, -> (type) { self.where(species: type) }
  scope :subtype, -> (subtype) { self.where(breed: subtype) }
  scope :loc_lost, -> (location) { self.where(loc_lost: location) }
  scope :gender, -> (gender) { self.where(gender: gender) }
  scope :age, -> (age) { self.where(age: age) }

  has_attached_file :avatar,
                    :styles => { :large => "600x600>",
                                  :medium => "300x300>",
                                  :thumb => "100x100>" },
                    :default_url => "/images/:style/No_image_available.png"

  validates_attachment_content_type :avatar,
                                    :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]

  validates_attachment_size :avatar, :less_than => 5.megabytes,
                                     :message => "Smaller please"

  validates_inclusion_of :lost, :in => [true, false]
  validates :species, :presence => true
  validates :breed, :presence => true
  validates :description, :presence => true
  validates :loc_lost, :presence => true
  validates_inclusion_of :gender, in: GENDERS
  validates_inclusion_of :age ,in: AGES

  belongs_to :user
  has_and_belongs_to_many :colors


  def color_ids
    self.colors.collect do |color|
      color.id
    end
  end

  def color_ids=(colors)
    self.colors = Color.find(colors)
  end

  def self.timed_destroy
    Pet.all.each do |pet|
      if Time.now > pet.updated_at + 60*60*24*180
        pet.destroy
      end
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # needs to be temporarily excluded for Heroku to work
  after_create :send_welcome_email

  ROLES = %w(admin user)
  has_many :pets, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates :role, presence: true, inclusion: { in: ROLES, message: "%{value} is not a valid role"}

  def lost_pets
    self.pets.select { |pet| pet.lost }
  end

  def found_pets
    self.pets.select { |pet| !pet.lost }
  end

  def send_welcome_email
    UserMailer.welcome_email(self).deliver
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # include Authentication

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  rescue_from CanCan::AccessDenied do |exception|
    flash[:alert] = 'In order to list a pet please sign in or sign up.'
    # redirect_to root_path
    redirect_to new_user_session_path
  end

  before_action :configure_permitted_parameters, if: :devise_controller?

protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :phone
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  def new
    @pet = Pet.find(params[:pet_id])
  end

  def create
    @message = Message.new(params)
    if params[:lost] == "true"
      UserMailer.found_pet_email(@message).deliver
      flash[:notice] = "An email to the pet owner has been sent!"
      redirect_to pets_path
    else
      UserMailer.lost_pet_email(@message).deliver
      flash[:notice] = "An email has been sent to the finder of this pet!"
      redirect_to pets_path
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def index
    @pets = Pet.all
    @lost = Pet.lost.last(5)
    @found = Pet.found.last(5)
  end
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  def index
    authorize! :index, Pet
    @pets = Pet.all
    @lost = Pet.lost.last(5)
    @found = Pet.found.last(5)
  end

  def search
    authorize! :index, Pet
    @pets = Pet.filter(filtering_params).order('created_at DESC').page(params[:page]).per_page(20)
  end

  def show
    @pet = Pet.find(params[:id])
    authorize! :show, @pet
    if @pet.nil?
      render 'public/404.html'
    end
  end

  def new
    authorize! :create, Pet
    if !current_user
      render "please_sign_in"
    else
      @pet = Pet.new(pet_params)
      render 'new'
    end
  end

  def create
    authorize! :create, Pet
    @pet = Pet.new(pet_params)
    if @pet.save
      redirect_to pets_path
    else
      render 'new'
    end
  end

  def edit
    @pet = Pet.find(params[:id])
    authorize! :update, @pet
    if !current_user
      render "please_sign_in.html.erb"
    else
      render 'edit'
    end
  end


  def update
    @pet = Pet.find(params[:id])
    authorize! :update, @pet
    if @pet.update pet_params
      redirect_to pets_path
    else
      render 'edit'
    end
  end

  def destroy
    @pet = Pet.find(params[:id])
    authorize! :destroy, @pet
    @pet.destroy
    flash[:notice] = 'Pet listing successfully deleted.'
    redirect_to pets_path
  end




private
  def pet_params
    params.require(:pet).permit(:user_id, :species, :breed, :loc_lost, :lost, :description, :gender, :age, :avatar, color_ids: [])
  end


  def filtering_params
    params.require(:search).permit(:user_id, :species, :gender, :age, :breed, :loc_lost, :lost)
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  load_and_authorize_resource

  def index
    @user = self.current_user
  end

  def new
    @user = User.new
  end

  def create
    new_params = user_params.merge({ password: "74108520" })
    @user = User.new(new_params)
    if @user.save
      UserMailer.welcome_email(@user).deliver
      flash[:notice] = "#{@user.email} successfully added as admin."
      redirect_to users_path
    else
      render 'new'
    end
  end

  def show
    @user = User.find_by_id(params[:id])
  end

  def destroy
    @user = User.find params[:id]
    @user.destroy
    flash[:notice] = "User successfully deleted."
    redirect_to users_path
  end

private

  def user_params
    params.require(:user).permit(:id, :email, :role, :phone)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Lost Pet Finder</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div class="container">
    <div class="sign_in_links">
      <div class="pull-left">
        <%= link_to 'Home', root_path%>
      </div>
      <div class="pull-right">
        <%if user_signed_in?%>
          <span class="logged-in-as" align='right'>Logged in as <strong><%= current_user.email %></strong></span>
          <%= link_to 'Edit profile', edit_user_registration_path %> |
          <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
        <%else%>
          <%= link_to "Sign In or Sign Up", new_user_session_path %>
        <%end%>
      </div>
    </div>

    <%= flash[:alert] %>
    <%= flash[:notice] %>

    <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4 header-images">
      <%= link_to image_tag('OHS-Logo-2011.png', class: 'logo'), root_path %>
    </div>

    <div class="col-xs-8 col-sm-8 col-md-8 col-lg-8 header-images">
      <%= link_to image_tag('header4.jpg', height: '8%', width: '100%', class: 'img-responsive'), root_path %>
    </div>
      <%= yield %>
    </div>
  </div>

  <br><br><br><br><br><br><br><br>
  <div class="container footer">
    <div class="panel-footer" align='center'>
      Made by Us.
    </div>
  </div>

</body>
</html>

app/views/messages/new.html.erb
<div class='row'>
  <div class='col-md-6'>
    <%= form_tag pet_messages_path(@pet) do %><br><br>

      <%= label_tag :message %> <br>
      <% if current_user %>
        <%= hidden_field_tag 'sender_email', current_user.email %>
      <%else%>
        <%= text_field_tag 'sender_email', nil, {placeholder:  'Please enter email:', class: 'form-control'} %>
      <%end%>
<br>
      <% if @pet.lost %>
        <%= text_area_tag :message, 'I may have found your lost pet.', class: 'form-control' %>
      <% else %>
        <%= text_area_tag :message, 'I may know the owner of that pet!', class: 'form-control' %>
      <% end %>

      <br><br>
      <%= hidden_field_tag 'owner_email', @pet.user.email %>
      <%= hidden_field_tag 'owner_phone', @pet.user.phone %>
      <%= hidden_field_tag 'lost', @pet.lost %>

      <br>
      <%= submit_tag 'Send Email', class: 'btn btn-primary' %>
      <br><br><br><br><br><br>
    <% end %>
  </div>
</div>

app/views/pages/index.html.erb
<br><br>

<div class="row-fluid">
  <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
    <br>
    <p>
      <%= link_to "Report a Lost Pet", new_pet_path(pet: { lost: true }), class: "btn btn-default test" %>
    </p>
    <br>
    <p>
      <%= link_to "Report a Found Pet", new_pet_path(pet: { lost: false }), class: "btn btn-default test" %>
    </p>
    <br>
    <p>
      <%= link_to 'Search Lost Pets', pets_search_path(search: { lost: true }), class: "btn btn-default test1" %>
    </p>
    <br>
    <p>
      <%= link_to 'Search Found Pets', pets_search_path(search: { lost: false}), class: "btn btn-default test1" %>
    </p>
    <br>
    <p>
      <%= link_to "View List of Pets", pets_path, class: "btn btn-default test2" %>
    </p>
    <br>
    <%if can? :index, User%>
      <p align='center'><%= link_to 'Users directory', users_path %></p>
    <%end%>
  </div>
</div>

<div class="row-fluid">
  <div class="col-xs-12 col-sm-12 col-md-8 col-lg-8">
    <br>
    <h1 class="green">Welcome to the pet finder!</h1>
    <p>
      Literally foursquare fashion axe, locavore letterpress mustache freegan American Apparel. Ennui retro paleo locavore, twee McSweeney's whatever. Sriracha American Apparel YOLO, fingerstache pug narwhal single-origin coffee dreamcatcher pork belly chillwave Godard locavore. Bitters small batch banh mi, ethnic distillery you probably haven't heard of them Schlitz aesthetic authentic. Tote bag vegan retro scenester.]
    </p>
    <br>
    <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
      <div class="display">
        Recently Lost Pets:
      </div>
      <%@lost.each do |pet|%>
        <br>
        <%= render pet,  size: :thumb, dimension: '100px', show_full: false %>
      <%end%>
      <br>
      <%if Pet.lost.length > @lost.length%>
        <%=link_to 'See more here', pets_search_path(search: { lost: true }), class: "btn btn-primary"%>
      <%end%>
      <% if @lost.empty? %>
        <h3>There are presently no lost pets </h3>
      <%end%>
    </div>

    <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
      <div class="display">
        Recently Found Pets:
      </div>
      <%@found.each do |pet|%>
        <br>
        <%= render pet,  size: :thumb, dimension: '100px', show_full: false %>
      <%end%>
      <br>
    <%if Pet.found.length > @found.length%>
      <%=link_to 'See more here', pets_search_path(search: { lost: false }), class: "btn btn-primary"%>
    <%end%>
    <% if @found.empty? %>
      <h3>There are presently no found pets </h3>
    <%end%>
    </div>

  </div>
</div>

app/views/pets/_filter.html.erb
<div class="display1">
  <h3>Filter:</h3>
</div>
<%= form_tag pets_search_path, method: :get  do %>
  <div class="form-group">
    <br>
    <%= select_tag 'search[lost]', options_for_select([['Lost', 'true'], ['Found', 'false']], params[:search][:lost]), prompt: 'Lost or Found', class: 'form-control' %>
    <br>

    <%= select_tag 'search[species]', options_for_select(Pet::TYPES, params[:search][:species]), prompt: 'Pet type', class: 'form-control' %>
    <br>

    <%= select_tag 'search[loc_lost]', options_for_select(Pet::LOCATIONS, params[:search][:loc_lost]), prompt: 'Location', class: 'form-control'%>
    <br>


    <%= select_tag 'search[gender]', options_for_select(Pet::GENDERS, params[:search][:gender]), prompt: 'Gender', class: 'form-control'%>
    <br>
    <%= select_tag 'search[age]', options_for_select(Pet::AGES, params[:search][:age]), prompt: 'Age', class: 'form-control'%>
    <br>

    <%= submit_tag 'Filter',  class: 'form-control filter' %>
  </div>
  <%end%>
</div>

app/views/pets/_form.html.erb
<div class="col-xs-12 col-sm-12 col-md-5 col-lg-5">
  <% owner = (@pet.user || current_user) %>
  <%= bootstrap_form_for(@pet) do |f| %>
    <%= f.hidden_field :user_id, value: owner.id %>
    <div class="field">
      <%= f.select :species, options_for_select(Pet::TYPES, @pet.species),
          label: "Please enter type of pet" %>
    </div>

    <br>

    <div class="field">
      <%= f.text_field :breed,
                       label: "Breed",
                       placeholder: "Please enter a breed" %>
    </div>

    <br>

    <div class="field">
        <%= f.select :loc_lost, options_for_select(Pet::LOCATIONS, @pet.loc_lost),
        label: (@pet.lost ? "Area last seen in" : "Area pet found") %>
    </div>
    <br><br>

    <div class="field">
      <%= f.text_area :description, size: "35x7",
                                    label: "Description",
                                    placeholder: "Please enter a description of the animal"  %><br>
    </div>
    <%if @pet.created_at.present?%>
      <%if @pet.avatar.present?%>
        <p>Current photo:</p>
        <p>
          <%= image_tag @pet.avatar.url(:medium), class: "img-responsive" %>
        </p>
      <%else%>
        <p>
          <%= image_tag("No_image_available.png", height: '50%', width: '50%', class: "img-responsive")  %>
        </p>
      <%end%>
    <%end%>
    <%= f.file_field :avatar, label: (@pet.created_at ? "Edit photo:" : "Add photo:") %>
<br><br><br>
</div>

<div class="col-xs-12 col-sm-12 col-md-5 col-lg-5">
    <div class="field">
      <%= f.select :gender, options_for_select(Pet::GENDERS, @pet.gender),
          label: "Please enter gender of pet" %>
    </div>

    <br>

    <div class="field">
      <%= f.select :age, options_for_select(Pet::AGES, @pet.age),
          label: "Please enter age of pet" %>
    </div>
    <br>

    <div class="field">
    <strong>Please select colors:</strong>
      <br><br>

      <% Color.all.each do |color| %>
        <input id='pet_colors_<%= color.id %>' name='pet[color_ids][]' type='checkbox' value='<%= color.id %>'
          <%= if @pet.colors.include? color then 'checked=checked' end %>
        />
        <label for='pet_colors_<%= color.id %>'>
          <%= color.name %>
        </label>
        <br>
      <%end%>
    </div>

    <br><br>
      <%= f.hidden_field :lost %>

    <br><br>
  </div>
  <br><br><br>

    <%= f.submit class: "btn btn-primary"%>
    <%end%>
</div>

app/views/pets/_pet.html.erb
<%if pet.avatar.present?%>
  <%= link_to image_tag(pet.avatar.url(size), class: "img-responsive"), pet_path(pet) %>
<%else%>
  <%= link_to image_tag("No_image_available.png", height: dimension, width: dimension), pet_path(pet) %>
<%end%>
<p><%= link_to "Species: #{pet.species}", pet_path(pet) %></p>
<%owner = pet.user%>
<%if can? :show, owner%>
  <p>Owner: <%= link_to owner.email, user_path(owner) %></p>
<%end%>
<p>Post created: <%= pet.created_at.strftime(" %B %d, %Y") %></p>
<%if show_full%>
  <p><%= pet.lost ? 'Last seen at' : 'Found near' %>: <%= pet.loc_lost %></p>
  <p>Breed: <%= pet.breed %></p>
  <p>Gender: <%= pet.gender %></p>
  <p>Age: <%= pet.age%></p>
  <p>Description:  <%= pet.description %></p>
  <% unless pet.colors.empty? %>
    <p>Colors:</p>
    <ul>
      <%pet.colors.each do |color|%>
        <li><%= color.name %></li>
      <%end%>
    </ul>
  <%end%>
<%end%>

app/views/pets/edit.html.erb
<h1>Edit pet information</h1>

<%= render("layouts/errors", :object => @pet) %>

<%= render 'form' %>
<br>
<p><%=link_to "Return to pet index", pets_path %></p>

app/views/pets/index.html.erb
<br>
<div class='container'>
  <div class='row-fluid'>
    <div class='col-xs-12 col-sm-6 col-md-6 col-lg-6'>
      <br>
      <div class='display1'>
        <h3> Most recent lost pets :</h3>
      </div>
      <%if @lost.empty?%>
        <h3>There are presently no lost pets </h3>
      <%end%>
      <%@lost.each do |pet|%>
        <br>
        <%= render pet, size: :medium, dimension: '200px', show_full: true %>
      <%end%>
    </div>

    <div class='col-xs-12 col-sm-6 col-md-6 col-lg-6'>
      <br>
      <div class='display1'>
        <h3>Most recent found pets:</h3>
      </div>
      <% if @found.empty? %>
        <h3>There are presently no found pets </h3>
      <%end%>
      <%@found.each do |pet|%>
        <br>
        <%= render pet, size: :medium, dimension: '200px', show_full: true %>
      <%end%>
    </div>

    <br><br><br><br><br><br><br><br>
  </div>
</div>

app/views/pets/new.html.erb
<%if @pet.lost%>
  <h3>List a lost pet:</h3>
<%else%>
  <h3>List a found pet</h3>
<%end%>
<br>
<%= render("layouts/errors", :object => @pet) %>
<div class="row">
  <%= render 'form' %>
  <br>
  <p><%= link_to "Return to pet index", pets_path %></p>
</div>
<br><br><br>

app/views/pets/search.html.erb
<br>
<div class="container">
  <div class="row-fluid">

    <div class="col-xs-12 col-sm-12 col-md-3 col-lg-3">
      <br>
      <%= render 'filter' %>
    </div>
      <div class="col-xs-12 col-sm-12 col-md-6 col-lg-9">
        <br>
        <div class="display1">
          <h3>Pet listings :</h3>
        </div>
        <p>(<%= @pets.count %> out of <%= Pet.all.count %> total)</p>
        <%@pets.each do |pet|%>
          <br>

              <%= render pet, size: :large, dimension: '350px', show_full: true %>
        <%end%>
        <%= will_paginate @pets %>
      </div>
    <br><br><br><br><br><br><br><br><br><br><br>
  </div>
</div>

app/views/pets/show.html.erb
<%= content_for(:title, "Show Pet | Pet Finder" ) %>

<%if @pet.lost%>
  <p><h1>Reported Lost:</h1></p>
<%else%>
  <p><h1>Reported Found:</h1></p>
<%end%>

<br>

<div class="row-fluid">
  <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
    <%= render @pet, size: :large, dimension: '300px', show_full: true %>
  </div>
</div>

<div class="row-fluid">
  <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
    <%if ( !current_user || ( !current_user.pets.include?(@pet) || current_user.role == 'admin' ))%>
      <%if @pet.lost%>
        <p><%= link_to "Have you seen me?", new_pet_message_path(@pet), class: "btn btn-danger" %>
      <%else%>
        <p><%= link_to "Do you know who I belong to?", new_pet_message_path(@pet), class: "btn btn-danger" %>
      <%end%>
    <%end%>
    <p><%= link_to "Return to pet index", pets_path, class: "btn btn-danger" %></p>
    <%if can? :edit, @pet%>
      <p><%= link_to "Edit This Listing", edit_pet_path, class: "btn btn-danger" %></p>
    <%end%>
    <%if can? :destroy, @pet%>
      <p><%= link_to "Delete This Listing", pet_path(@pet),
                             data: {confirm: "You sure?",
                                    method: "delete"},
                             class: "btn btn-danger" %></p>
    <%end%>
    <br><br><br><br><br><br><br>
  </div>
</div>
</div>

app/views/users/_form.html.erb
  <div class='col-xs-12 col-sm-12 col-md-6 col-lg-6'>

<%= form_tag do %>
  <%= hidden_field :user, :role, value: 'admin' %>
  <div class='form-group '>
    <%= label :user, :email %><br>
    <%= text_field :user, :email %>
  </div>
  <br><br>
  <%= submit_tag "Create Admin", class: 'btn btn-primary' %>

<% end %>
<br><br><br>

</div>

app/views/users/index.html.erb
<p><%= @user.email %> is an administrator</p>
<ul>
  <% User.all.each do |user| %>
    <li><%= link_to "#{user.email}", user_path(user) %>
      <% if can? :delete, user %>
        | <%= link_to 'Delete account', user_path(user), data: { confirm: 'You sure?', method: 'delete' } %>
      <% end %>
    </li>
  <% end %>
</ul>

<% if can? :create, User %>
  <p><%= link_to 'Create new admin', users_admin_new_path %></p>
<% end %>

app/views/users/new.html.erb
<h1>Create new admin account</h1>

<%= render 'layouts/errors', object: @user %>

<%= render 'form' %>

app/views/users/show.html.erb
<p><%= @user.email %></p>
<p><%= @user.lost_pets.count %> lost pets</p>
<p><%= @user.found_pets.count %> found pets</p>